# Generated by Django 4.1 on 2022-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.TextField()),
                ('var2', models.TextField()),
                ('var3', models.TextField()),
            ],
        ),
    ]
