# Generated by Django 4.1 on 2022-08-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Small',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.TextField()),
                ('s2', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cal',
            name='s_id_asdf',
            field=models.ForeignKey(db_column='s_id', default='', on_delete=django.db.models.deletion.CASCADE, related_name='small', to='calendarApp.small'),
            preserve_default=False,
        ),
    ]
